---
title: "Linea_model"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
```{r}
#1
lions <- read.csv('lions.csv')
#2
head(lions)
#3 
#response variable: age, explanatory variable: black dots
b <- ggplot( data = lions, aes(x = black, y = age))+ geom_point()
b
```
```{r}
#fit a linear model
out <- lm(age ~ black, data = lions)
slo <- coef(summary(out))['black', 'Estimate']
int <- coef(summary(out))['(Intercept)','Estimate']
b <- ggplot( data = lions, aes(x = black, y = age))+ geom_point() + geom_abline(aes(intercept = int, slope = slo, color = 'blue'))
b
#4
confint(out, level = 0.95)
#5
drop1(out, test = 'F')
anova(out)
#6
plot(out)

#7
lionssans <- lions %>% subset(age<13.1)
out2 <- lm(age ~ black, data = lionssans)
summary(out2)
```

```{r}
#Prediction

b

# 2
new.vals <- data.frame(black=seq(min(lions$black),max(lions$black), length=20))
conf_int <- predict(out, newdata = new.vals, interval = "confidence")

#in base... 
plot(x=lions$black, y=lions$age, xlab='Amount of black in nose', ylab='Age', pch=16, col='red', las=1) + abline(out, lwd=2, col='blue') + lines(x=new.vals[,'black'], y=conf_int[,'lwr'], lwd=2, lty=3, col='blue') + lines( x = new.vals[,'black'], y = conf_int[, 'upr'], lwd =2, lty =2, col ='blue')

#inggplot....
ggplot( data = lions, aes(x = black, y = age))+ geom_point() + geom_abline(aes(intercept = int, slope = slo, color = 'blue')) + geom_smooth(method=lm , color="red", fill="#69b3a2", se=TRUE)


#4
pred <- predict(out, newdata = new.vals, interval = "prediction") 
plot(x=lions$black, y=lions$age, xlab='Amount of black in nose', ylab='Age', pch=16, col='red', las=1) + abline(out, lwd=2, col='blue') + lines(x=new.vals[,'black'], y=conf_int[,'lwr'], lwd=2, lty=3, col='blue') + lines( x = new.vals[,'black'], y = conf_int[, 'upr'], lwd =2, lty =2, col ='blue') + lines( x = new.vals[,'black'], y = pred[, 'upr'], lwd =2, lty =2, col ='green') + lines( x = new.vals[,'black'], y = pred[, 'lwr'], lwd =2, lty =2, col ='green')
```
```{r}
#effects of light treatment on circadian rhythms
#1
knee <- read_csv('knees.csv')
#2
head(knee)

#3
summary(knee)

#treatment variable is a character 
knee$treatment <- as.factor(knee$treatment)
class(knee$treatment)

```


